###############################################################
# This Dockerfile will build the container NGINX
###############################################################

FROM nginx

LABEL Quentin Tshaimanga