###############################################################
# This Dockerfile will build the container MONGO
###############################################################

FROM mongo:latest

LABEL Quentin Tshaimanga

# COPY ./config/mongodb.conf /etc/mongo/mongod.conf