############################################################
# This Dockerfile will build the container Elasticsearch
############################################################

FROM docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.3

LABEL Quentin Tshaimanga
