version: '3'
services:
  debian:
    build: ./debian
    container_name: service-debian
    ports:
      - 80:80
    networks:
      - snips-net
    tty: true

networks:
  snips-net:
      driver: bridge