version: '2.2'
services:
  elasticsearch:
    build: ./elasticsearch
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "ELASTIC_PASSWORD=admin"
      - "KIBANA_PWD=admin"
      - "NODE_NAME=es1"
      - "HOSTS=127.0.0.1"
    volumes:
      # - ${ES}:/usr/share/elasticsearch/config/elasticsearch.yml
      - ${ESDATA1}:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      # - 9300:9300
    networks:
      - esnet
  elasticsearch2:
    build: ./elasticsearch
    container_name: elasticsearch2
    environment:
      - cluster.name=docker-cluster
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
      - "NODE_NAME=es1"
    volumes:
      - ${ESDATA2}:/usr/share/elasticsearch/data
    networks:
      - esnet
  elasticsearch3:
    build: ./elasticsearch
    container_name: elasticsearch3
    environment:
      - cluster.name=docker-cluster
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
      - "NODE_NAME=es3"
    volumes:
      - ${ESDATA3}:/usr/share/elasticsearch/data
    networks:
      - esnet
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.2.3
    container_name: kibana
    environment:
      - "ELASTICSEARCH_HOST=elasticsearch"
      - "ELASTICSEARCH_PORT=9200"
      - "ELASTICSEARCH_URL=http://elasticsearch:9200/"
      - "ELASTICSEARCH_USERNAME=elastic"
      - "ELASTIC_PASSWORD=admin"
      - "KIBANA_PWD=admin"
    # volumes:
      # - ${KIBANA}:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601
    networks:
      - esnet
    depends_on: 
      - elasticsearch
    links:
      - elasticsearch

networks:
  esnet:
      driver: bridge