version: '3'
services:
  elasticsearch:
    build: ./elasticsearch
    container_name: 'service-elk'
    environment:
      - cluster.name=docker-cluster
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "ELASTIC_PASSWORD=admin"
      - "KIBANA_PWD=admin"
      - "NODE_NAME=es1"
      - "HOSTS=127.0.0.1"
    volumes:
      # - ${ES}:/usr/share/elasticsearch/config/elasticsearch.yml
      - ${ESDATA1}:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - es-net
  elasticsearch2:
    build: ./elasticsearch
    container_name: 'service-elk2'
    environment:
      - cluster.name=docker-cluster
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=service-elk"
      - "NODE_NAME=es1"
    volumes:
      - ${ESDATA2}:/usr/share/elasticsearch/data
    networks:
      - es-net
  elasticsearch3:
    build: ./elasticsearch
    container_name: 'service-elk3'
    environment:
      - cluster.name=docker-cluster
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=service-elk"
      - "NODE_NAME=es3"
    volumes:
      - ${ESDATA3}:/usr/share/elasticsearch/data
    networks:
      - es-net
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.2.3
    container_name: 'service-kibana'
    environment:
      - "ELASTICSEARCH_HOST=service-elk"
      - "ELASTICSEARCH_PORT=9200"
      - "ELASTICSEARCH_URL=http://service-elk:9200/"
      - "ELASTICSEARCH_USERNAME=elastic"
      - "ELASTIC_PASSWORD=admin"
      - "KIBANA_PWD=admin"
    # volumes:
      # - ${KIBANA}:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601
    networks:
      - es-net
    depends_on: 
      - elasticsearch
    links:
      - elasticsearch

networks:
  es-net:
      driver: bridge