version: '3'
services:
  node:
    tty: true
    build: 
      context: ./node
      args:
        NODE_ENV: ${NODE_ENV}
    container_name: 'service-polly'
    volumes:
      - ${NODE_PATH}:/var/www/express
    ports:
      - '3000-3020:3000-3020'
    command: npm run ${NODE_ENV}
    networks:
      - node-net
      
networks:
  node-net:
    driver: bridge