version: '3'
services:
  node:
    tty: true
    build: 
      context: ./node
      args:
        NODE_ENV: ${NODE_ENV}
    container_name: 'service-api'
    volumes:
      - ./node/express:/var/www/express
    ports:
      - '7000-7020:7000-7020'
    command: npm run ${NODE_ENV}
  nginx:
    tty: true
    build: ./nginx
    container_name: 'service-nginx'
    ports:
      - '80:80'

networks:
  esnet:
      driver: bridge