version: '3'
services:
  node:
    tty: true
    build: 
      context: ./node
      args:
        NODE_ENV: ${NODE_ENV}
    container_name: 'service-express'
    volumes:
      - ./node/express:/var/www/express
    ports:
      - '3000-3004:3000-3004'
      - '7000-7004:7000-7004'
    command: npm run ${NODE_ENV}
  nginx:
    tty: true
    build: ./nginx
    container_name: 'service-nginx'
    ports:
      - '80:80'

networks:
  esnet:
      driver: bridge