version: '3'
networks:
  docker-polly_node-net:
    external: true
  docker-elk_es-net:
    external: true
  docker-mongo_mongo-net:
    external: true
services:
  node:
    tty: true
    build: 
      context: ./node
      args:
        NODE_ENV: ${NODE_ENV}
    container_name: 'service-api'
    volumes:
      - ${NODE_PATH}:/var/www/express
    ports:
      - '7000-7020:7000-7020'
    command: npm run ${NODE_ENV}
  nginx:
    tty: true
    build: ./nginx
    container_name: 'service-nginx'
    ports:
      - '80:80'
    networks:
      - default
      - docker-polly_node-net
      - docker-elk_es-net
      - docker-mongo_mongo-net

