version: '3'
services:
  mongo:
    tty: true
    build: ./mongo
    container_name: 'service-mongo'
    restart: always
    ports:
      - '27017:27017'
    volumes:
     - ${MONGO_DATA_PATH}:/data/db
     - "$PWD/mongo-entrypoint/:/docker-entrypoint-initdb.d/"
    environment:
      MONGO_INITDB_DATABASE: ${DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${ROOT_PASSWORD}
    command: mongod
  mongo-express:
    tty: true
    build: ./mongo-express
    container_name: 'service-mongo-express'
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - 'mongo'
    environment:
      ME_CONFIG_MONGODB_ENABLE_ADMIN: 'true'
      ME_CONFIG_MONGODB_AUTH_DATABASE: ${DATABASE}
      ME_CONFIG_MONGODB_AUTH_USERNAME: ${AUTH_USERNAME}
      ME_CONFIG_MONGODB_AUTH_PASSWORD: ${AUTH_PASSWORD}
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${ADMINUSERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${ADMINPASSWORD}
      ME_CONFIG_BASICAUTH_USERNAME: ${BASICAUTH_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${BASICAUTH_PASSWORD}

networks:
  esnet:
      driver: bridge