###############################################################
# This Dockerfile will build the container MONGO-EXPRESS
###############################################################

FROM mongo-express:latest

LABEL Quentin Tshaimanga

COPY ./config/config.js /node_modules/mongo-express/config.js
